# Generated by Django 4.2.28 on 2026-02-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testexecution",
            name="browser",
            field=models.CharField(default="chrome", max_length=20),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="browserbase_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="device",
            field=models.CharField(default="desktop", max_length=20),
        ),
    ]
