git fetch origin tag # Generated by Django 4.2.28 on 2026-02-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_testexecution_browser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testexecution",
            name="live_view_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
