# Generated by Django 4.2.28 on 2026-02-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_testexecution_browser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="url",
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="testexecution",
            name="url",
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="url",
            field=models.URLField(max_length=2000),
        ),
    ]
