# Generated by Django 4.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_testexecution_browser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testexecution",
            name="is_scheduled",
            field=models.BooleanField(default=False),
        ),
    ]
