# Generated by Django 4.2.28 on 2026-02-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_live_view_url_to_test_execution"),
        ("core", "0003_increase_url_max_length"),
    ]

    operations = []
