# Generated by Django 4.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_testexecution_browser_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="testexecution",
                    name="is_scheduled",
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE test_execution ADD COLUMN IF NOT EXISTS is_scheduled boolean NOT NULL DEFAULT false;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
