# Generated by Django 4.2.28 on 2026-02-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_merge_20260224_2238"),
        ("core", "0004_testexecution_is_scheduled"),
    ]

    operations = []
