# Generated by Django 4.2.28 on 2026-02-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_merge_20260225_0001"),
        ("core", "0005_testexecution_is_scheduled"),
    ]

    operations = []
